
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
let GAMES=[], MODULES={}, RUN=null, PICKS=[];
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
async function loadData(){
  GAMES=await fetch('./data/games.json').then(r=>r.json());
  for(const g of GAMES){ MODULES[g.key]=await fetch(`./data/${g.key}.json`).then(r=>r.json()); }
}
function store(){ return JSON.parse(localStorage.getItem('fafa_stable_modules')||'{"sessions":{}}'); }
function save(v){ localStorage.setItem('fafa_stable_modules', JSON.stringify(v)); }
function gameByKey(k){ return GAMES.find(g=>g.key===k); }
function scoreBase(){ const d=qs('#difficulty')?.value||'moyen'; return d==='facile'?1100:d==='moyen'?1250:1400; }
function ageLabel(a){ return a==='kids'?'Enfants':a==='teens'?'Ados':'Tous publics'; }
function playTone(type='ok'){ try{ const c=new(window.AudioContext||window.webkitAudioContext)(); const o=c.createOscillator(), g=c.createGain(); o.connect(g); g.connect(c.destination); o.frequency.value=type==='ok'?660:type==='bad'?220:type==='start'?520:420; g.gain.value=.03; o.start(); o.stop(c.currentTime+.16);}catch(e){} }
function renderHome(){
  qs('#app').innerHTML=`<div class="hero"><div><img src="./assets/logo.png" class="hero-logo" alt="logo"></div><div><div class="kicker">FAFATRAINING GAME ARENA</div><h1>ENTRE DANS LE JEU.</h1><div class="subtitle">Deux modules stables, immersifs et visuellement plus forts. Chaque univers a son propre mood, sa propre histoire et son propre style de défis.</div></div><div class="hero-stats"><div class="stat green"><strong>2</strong><span>univers stables</span></div><div class="stat blue"><strong>8</strong><span>défis variés</span></div><div class="stat pink"><strong>sons</strong><span>dynamiques</span></div><div class="stat gold"><strong>propre</strong><span>base solide</span></div></div></div><div class="tabs"><button class="tab active" onclick="showAdmin()">Administrateur</button><button class="tab" onclick="showManualEntry()">Jouer</button><button class="tab" onclick="showInfo()">Notes</button></div><div id="main"></div>`;
  showAdmin();
}
function setTab(name){ qsa('.tab').forEach(b=>b.classList.toggle('active',b.textContent.trim()===name)); }
function showAdmin(){
  setTab('Administrateur');
  const first=GAMES[0];
  qs('#main').innerHTML=`<section class="panel"><h2 class="section-title">Préparer une session</h2><div class="notice">Préparation rangée, claire et utile. Le score de départ s’adapte automatiquement à la difficulté. Les codes d’équipe sont personnalisables.</div><div class="grid4"><div><label>Nom de session</label><input id="sessionName" value="Session Arena"></div><div><label>Univers / mode</label><select id="gameSelect" onchange="previewGame()">${GAMES.map(g=>`<option value="${g.key}">${g.title}</option>`).join('')}</select></div><div><label>Âge</label><select id="ageSelect"><option value="all">Tous publics</option><option value="kids">Enfants</option><option value="teens">Ados</option></select></div><div><label>Durée</label><select id="duration"><option value="30">30 min</option><option value="45" selected>45 min</option><option value="60">60 min</option></select></div></div><div class="grid4" style="margin-top:14px"><div><label>Difficulté</label><select id="difficulty" onchange="updateScore()"><option value="facile">Accessible</option><option value="moyen" selected>Équilibré</option><option value="difficile">Challenge</option></select></div><div><label>Nombre d’équipes</label><select id="teamCount" onchange="renderTeams()"><option value="2">2 équipes</option><option value="3" selected>3 équipes</option><option value="4">4 équipes</option></select></div><div><label>Score de départ auto</label><input id="baseScore" disabled value="1250"><div class="hint-text">Calculé selon difficulté.</div></div><div><label>Mode</label><input disabled value="Compétitif immersif"></div></div><div id="gamePreview"></div><div class="notice">Nom et code des équipes : modifiables librement.</div><div id="teamsBox"></div><div class="btns"><button class="btn main" onclick="createSession()">Créer la session</button></div><div id="sessionOutput"></div></section>`;
  renderTeams(); updateScore(); previewGame();
}
function renderTeams(){ const n=Number(qs('#teamCount')?.value||3), defs=['ALPHA','BRAVO','CHARLIE','DELTA']; qs('#teamsBox').innerHTML=`<div class="grid3">${Array.from({length:n},(_,i)=>`<div class="card"><div class="pills"><span class="pill">Équipe ${i+1}</span></div><label>Nom d’équipe</label><input class="teamName" value="Équipe ${i+1}"><label style="margin-top:8px">Code</label><input class="teamCode" value="${defs[i]}"></div>`).join('')}</div>`; }
function updateScore(){ if(qs('#baseScore')) qs('#baseScore').value=scoreBase(); }
function previewGame(){ const g=gameByKey(qs('#gameSelect').value); qs('#gamePreview').innerHTML=`<div class="card" style="--accent:${g.color};margin-top:14px;background:${g.bg}"><div class="pills"><span class="pill">${esc(g.family)}</span><span class="pill">${esc(g.title)}</span></div><h3>${esc(g.tagline)}</h3><div class="small">${esc(g.intro)}</div></div>`; }
function createSession(){ const id='ga-'+Date.now(), names=qsa('.teamName').map(x=>x.value.trim()), codes=qsa('.teamCode').map(x=>x.value.trim().toUpperCase()), session={id,name:qs('#sessionName').value.trim(),gameKey:qs('#gameSelect').value,age:qs('#ageSelect').value,duration:Number(qs('#duration').value),difficulty:qs('#difficulty').value,baseScore:Number(qs('#baseScore').value),teams:names.map((n,i)=>({name:n||`Équipe ${i+1}`,code:codes[i]||`TEAM${i+1}`,players:'',index:0,score:Number(qs('#baseScore').value),hints:0}))}; const s=store(); s.sessions[id]=session; save(s); const origin=location.origin&&location.origin!=='null'?location.origin+location.pathname:location.pathname; qs('#sessionOutput').innerHTML=`<div class="notice"><strong>Session créée.</strong> Tu peux ouvrir chaque équipe directement avec son lien.</div><div class="cards">${session.teams.map(t=>`<div class="card"><div class="pills"><span class="pill">${esc(t.name)}</span><span class="pill">${esc(t.code)}</span></div><div class="small">${origin}?player=1&session=${id}&team=${encodeURIComponent(t.code)}</div><div class="btns"><button class="btn main" onclick="navigator.clipboard.writeText('${origin}?player=1&session=${id}&team=${encodeURIComponent(t.code)}')">Copier</button><button class="btn alt" onclick="window.open('${origin}?player=1&session=${id}&team=${encodeURIComponent(t.code)}','_blank')">Ouvrir</button></div></div>`).join('')}</div>`; }
function showManualEntry(){ setTab('Jouer'); qs('#main').innerHTML=`<section class="panel"><h2 class="section-title">Entrée joueur</h2><div class="notice">Tu peux entrer ici avec l’identifiant de session et le code équipe si besoin.</div><div class="grid2"><div><label>ID session</label><input id="sid"></div><div><label>Code équipe</label><input id="tcode"></div></div><div class="btns"><button class="btn main" onclick="manualOpen()">Entrer</button></div></section>`; }
function manualOpen(){ const s=qs('#sid').value.trim(), t=qs('#tcode').value.trim(); history.replaceState({},'',`?player=1&session=${encodeURIComponent(s)}&team=${encodeURIComponent(t)}`); bootPlayer(); }
function showInfo(){ setTab('Notes'); qs('#main').innerHTML=`<section class="panel"><h2 class="section-title">Ce build contient</h2><div class="goal-grid"><div class="goal"><h4>2 univers stables</h4><div>Domination Nocturne et Odyssée Verte.</div></div><div class="goal"><h4>Flow solide</h4><div>Base stable, pas de page noire, pas de retour arrière après validation.</div></div><div class="goal"><h4>Prochaine étape</h4><div>Étendre ce niveau de finition à tous les autres univers.</div></div></div></section>`; }
function currentPlayer(team, idx){ const arr=(team.players||'').split(',').map(x=>x.trim()).filter(Boolean); return arr.length?arr[idx%arr.length]:team.name; }
function bootPlayer(){ const p=new URLSearchParams(location.search), sid=p.get('session'), code=p.get('team'); if(!(p.get('player')==='1'&&sid&&code)){ renderHome(); return; } const s=store().sessions[sid]; if(!s){ qs('#app').innerHTML=`<section class="panel"><div class="notice">Session introuvable.</div></section>`; return; } const team=s.teams.find(x=>x.code===code); if(!team){ qs('#app').innerHTML=`<section class="panel"><div class="notice">Équipe introuvable.</div></section>`; return; } const g=gameByKey(s.gameKey); qs('#app').innerHTML=`<div class="hero" style="background:${g.bg}"><div><img src="./assets/logo.png" class="hero-logo" alt="logo"></div><div><div class="kicker">${esc(g.title)}</div><h1>${esc(g.tagline)}</h1><div class="subtitle">${esc(g.intro)}</div></div><div class="hero-stats"><div class="stat green"><strong>${esc(team.code)}</strong><span>code équipe</span></div><div class="stat blue"><strong>${s.duration}</strong><span>minutes</span></div><div class="stat pink"><strong>${MODULES[s.gameKey].length}</strong><span>défis</span></div><div class="stat gold"><strong>${team.score}</strong><span>score départ</span></div></div></div><section class="panel"><h2 class="section-title">Avant de commencer</h2><div class="story">${esc(g.intro)}</div><div class="goal-grid" style="margin-top:14px"><div class="goal"><h4>Objectif</h4><div>${esc(g.goal)}</div></div><div class="goal"><h4>Règle utile</h4><div>${esc(g.rules)}</div></div><div class="goal"><h4>Cartes Bonus</h4><div>${esc(g.help)}</div></div></div><div class="grid2" style="margin-top:14px"><div><label>Nom d’équipe</label><input id="teamNameInput" value="${esc(team.name)}"></div><div><label>Joueurs (séparés par virgule)</label><input id="playersInput" value="${esc(team.players)}" placeholder="Lina, Tom, Hugo"></div></div><div class="btns"><button class="btn main" onclick="startGame('${sid}','${code}')">Lancer la mission</button></div></section>`; }
function startGame(sid,code){ const s=store(), session=s.sessions[sid], team=session.teams.find(x=>x.code===code); team.name=qs('#teamNameInput').value.trim()||team.name; team.players=qs('#playersInput').value.trim(); save(s); RUN={sid,code,attempts:0}; playTone('start'); renderChallenge(); }
function themeEvent(key, idx){ const map={domination_nocturne:['🌧 La pluie brouille les certitudes.','⚠️ Une autre équipe accélère peut-être déjà.','🌘 La nuit récompense les groupes les plus lucides.'], odyssee_verte:['🌿 Le terrain cache plus d’une issue.','🧭 Une fausse piste peut coûter cher.','✨ Une bonne lecture peut tout ouvrir.']}; const arr=map[key]||['⚡ La tension monte.']; return arr[idx%arr.length]; }
function renderChallenge(){ const s=store(), session=s.sessions[RUN.sid], team=session.teams.find(x=>x.code===RUN.code), game=gameByKey(session.gameKey), list=MODULES[session.gameKey], c=list[team.index]; const typeLabel={logic:'🧠 Logique',observation:'👁 Observation',deduction:'🔐 Déduction',strategy:'⚔️ Stratégie',navigation:'🧭 Orientation',pattern:'🔁 Motif',code:'🔐 Code',choice:'🎯 Choix'}[c.kind]||'Défi'; qs('#app').innerHTML=`<section class="screen" style="--accent:${game.color};background:${game.bg}"><div class="hud"><div class="hud-group"><div class="badge points">Score : ${team.score}</div><div class="badge time">Défi ${team.index+1}/${list.length}</div><div class="badge event">Cartes Bonus : ${team.hints}</div></div><div class="hud-group"><div class="badge">${session.duration} min</div></div></div><div class="notice">${esc(themeEvent(session.gameKey, team.index))}</div><div class="player-turn">🔥 C’EST À : ${esc(currentPlayer(team, team.index))} DE JOUER</div><div class="story">${esc(c.scene)}</div><h2 class="challenge-title">${esc(c.title)}</h2><div class="challenge-type">${typeLabel}</div>${c.visual?`<div class="visual">${esc(c.visual)}</div>`:''}<div class="story"><strong>Énigme :</strong><br>${esc(c.prompt)}</div><div class="freeclue"><strong>Indice discret gratuit :</strong><br>${esc(c.free_clue)}</div><div class="choice-grid">${c.options.map((o,i)=>`<button class="choice" onclick="pick('${['A','B','C','D'][i]}',this)">${esc(o)}</button>`).join('')}</div><div class="help-grid"><div class="help" onclick="useHint(1)"><h4>Carte Bonus I</h4><div>Petit guidage contre une légère pénalité.</div></div><div class="help" onclick="useHint(2)"><h4>Carte Bonus II</h4><div>Révélation forte contre grosse pénalité.</div></div><div class="help" onclick="validateChoice()"><h4>Valider</h4><div>Confirme votre choix pour cette énigme.</div></div></div><div id="feedback"></div></section>`; PICKS=[]; RUN.attempts=0; }
function pick(letter, el){ qsa('.choice').forEach(b=>b.classList.remove('selected')); el.classList.add('selected'); PICKS=[letter]; }
function useHint(level){ const s=store(), session=s.sessions[RUN.sid], team=session.teams.find(x=>x.code===RUN.code), c=MODULES[session.gameKey][team.index]; team.hints += 1; team.score=Math.max(0, team.score-(level===1?35:80)); save(s); playTone('hint'); qs('#feedback').innerHTML=`<div class="feedback help"><strong>${level===1?'Carte Bonus I':'Carte Bonus II'}</strong><br>${esc(level===1?c.help1:c.help2)}</div>`; }
function validateChoice(){ const s=store(), session=s.sessions[RUN.sid], team=session.teams.find(x=>x.code===RUN.code), c=MODULES[session.gameKey][team.index]; if(!PICKS.length){ qs('#feedback').innerHTML=`<div class="feedback bad">Choisis d’abord une réponse.</div>`; return; } const ok=PICKS[0]===c.answer; if(ok){ team.score += 120; save(s); playTone('ok'); const last=team.index>=MODULES[session.gameKey].length-1; qs('#feedback').innerHTML=`<div class="feedback ok"><strong>Excellent choix.</strong><br>${esc(c.explanation)}<br><br><strong>${esc(c.bonus)}</strong></div><div class="btns"><button class="btn main" onclick="${last?'finishRun()':'nextChallenge()'}">${last?'Voir le résultat':'Défi suivant'}</button></div>`; } else { RUN.attempts += 1; playTone('bad'); if(RUN.attempts<2){ team.score=Math.max(0,team.score-40); save(s); qs('#feedback').innerHTML=`<div class="feedback bad"><strong>Mauvaise piste.</strong><br>Vous avez encore une chance. Relisez la scène et tentez une meilleure lecture.<br><br><span class="small">Pénalité légère : -40 points.</span></div>`; } else { team.score=Math.max(0,team.score-80); save(s); const last=team.index>=MODULES[session.gameKey].length-1; qs('#feedback').innerHTML=`<div class="feedback bad"><strong>Défi perdu.</strong><br>Bonne réponse : <strong>${esc(c.answer)}</strong>.<br>${esc(c.explanation)}<br><br><span class="small">Vous passez au défi suivant. Aucun retour arrière possible.</span></div><div class="btns"><button class="btn main" onclick="${last?'finishRun()':'nextChallenge()'}">${last?'Voir le résultat':'Défi suivant'}</button></div>`; } } }
function nextChallenge(){ const s=store(), session=s.sessions[RUN.sid], team=session.teams.find(x=>x.code===RUN.code); team.index += 1; save(s); renderChallenge(); }
function finishRun(){ const s=store(), session=s.sessions[RUN.sid], team=session.teams.find(x=>x.code===RUN.code), game=gameByKey(session.gameKey); const mention=team.score>=1600?'Domination totale':team.score>=1350?'Très belle percée':team.score>=1100?'Mission tenue':'Survie sous pression'; qs('#app').innerHTML=`<section class="panel"><h2 class="section-title">Fin de mission</h2><div class="final-card"><div class="big-score">${team.score} pts</div><p><strong>${esc(team.name)}</strong> — ${mention}</p><p>Cartes Bonus utilisées : ${team.hints}</p></div><div class="goal-grid" style="margin-top:16px"><div class="goal"><h4>Ce qui a fait la différence</h4><div>Lecture, sang-froid et capacité à corriger vite après une première erreur.</div></div><div class="goal"><h4>Récompense</h4><div>Une fin plus marquante, plus propre et plus valorisante.</div></div><div class="goal"><h4>Suite logique</h4><div>Étendre ce niveau à tous les autres univers du logiciel.</div></div></div><div class="btns"><button class="btn main" onclick="history.replaceState({},'',location.pathname); renderHome();">Retour accueil</button></div></section>`; }
async function init(){ await loadData(); const p=new URLSearchParams(location.search); if(p.get('player')==='1') bootPlayer(); else renderHome(); }
init();
